### ISSUE TITLE
Split out inline-tags.js to a separate module

### ISSUE THREAD

**Issue by TimothyGu** [jadejs/jade-parser#7]
We already have void-elements, so why not split this out as well?

**Comment by ForbesLindesay** [comment]
The real difference is that void-elements are a generally applicable thing outside of Jade.  They live in a specification that lists the tags that are and are not inline.  inline-tags are very much specific to the pretty printing.  They don't actually mean anything outside of jade.

**Comment by TimothyGu** [comment]
Fair enough.
